'use client';

import { useEffect, useState } from 'react';
import { cities, events, source, stories } from './content';

const Arrow = () => <span aria-hidden="true">↗</span>;
function Brand() { return <span className="wordmark"><span>VIDA VAQUERA</span><span className="wordmark-sub">— DEL NORTE —</span></span>; }

export default function Home() {
  const [city, setCity] = useState('Todas las ciudades');
  const [period, setPeriod] = useState('proximos');
  const [today, setToday] = useState('2026-09-04');
  useEffect(() => { setToday(new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Tijuana', year:'numeric', month:'2-digit', day:'2-digit' }).format(new Date())); }, []);
  const shown = events.filter(e => (city === 'Todas las ciudades' || city === e.city) && (period === 'todos' || e.date >= today));
  return <>
    <a href="#contenido" className="skip-link">Saltar al contenido</a>
    <div className="topbar"><span>BAJA CALIFORNIA + SAN DIEGO</span><a href="https://medios-interes-activos.vercel.app/" target="_blank" rel="noopener noreferrer">UN MEDIO DE MIA <Arrow/></a></div>
    <header className="header wrap"><a href="#inicio" aria-label="Vida Vaquera del Norte, inicio"><Brand/></a><nav aria-label="Navegación principal"><a href="#agenda">La agenda</a><a href="#experiencias">Experiencias</a><a href="#historias">Historias y estilo</a><a href="#comunidad">La comunidad</a></nav><a className="header-cta" href="#agenda">Encuentra tu plan <Arrow/></a><details className="mobile-menu"><summary>Menú <span aria-hidden="true">☰</span></summary><nav aria-label="Navegación móvil"><a href="#agenda">La agenda</a><a href="#experiencias">Experiencias</a><a href="#historias">Historias y estilo</a><a href="#comunidad">La comunidad</a></nav></details></header>
    <main id="contenido">
      <section className="hero" id="inicio"><img className="hero-image" src="/norte.webp" alt="Escena ilustrativa de dos personas a caballo entre las colinas del norte al atardecer" fetchPriority="high"/><div className="hero-shade"/><div className="hero-content wrap"><p className="eyebrow"><span className="small-star">✦</span> DE AQUÍ. DE ALLÁ. DEL NORTE.</p><h1>Lo vaquero<br/>se lleva <em>dentro.</em></h1><p className="hero-description">Caballos, música, tradiciones y buenos planes.<br/>Un lugar para vivir lo que nos une,<br className="desktop-break"/> a ambos lados de la frontera.</p><a href="#agenda" className="button cream">Explora la agenda <span aria-hidden="true">↗</span></a><div className="hero-bottom"><span>VIDA VAQUERA, TODO EL AÑO.</span><a href="#experiencias" aria-label="Descubrir experiencias">SIGUE EL CAMINO <span aria-hidden="true">↓</span></a></div></div><span className="hero-edition" aria-hidden="true">RAÍCES PROFUNDAS.<br/>HORIZONTES ABIERTOS.</span></section>
      <div className="city-strip" aria-label="Nuestra comunidad">{cities.map((name, i) => <span key={name}>{i > 0 && <b aria-hidden="true">✦</b>}{name}</span>)}</div>

      <section className="agenda wrap section" id="agenda"><div className="section-heading"><div><p className="eyebrow wine">PONLE FECHA AL PLAN</p><h2>Nos vemos <em>por acá.</em></h2></div><p>Música, encuentros y motivos para salir.<br/>Consulta cada plan con su organizador.</p></div><div className="agenda-toolbar"><span className="agenda-label"><span aria-hidden="true">✦</span> LA AGENDA DEL NORTE</span><div className="filters"><label><span className="sr-only">Ciudad</span><select value={city} onChange={e => setCity(e.target.value)}><option>Todas las ciudades</option>{cities.map(c => <option key={c}>{c}</option>)}</select></label><label><span className="sr-only">Periodo</span><select value={period} onChange={e => setPeriod(e.target.value)}><option value="proximos">Próximas fechas</option><option value="todos">Todas las fechas · septiembre 2026</option></select></label></div></div>
        <div className="event-list" aria-live="polite">{shown.length ? shown.map(e => <article className="event-row" key={e.id}><div className="event-date"><span>{e.date.slice(8)}</span><span>SEP · 2026</span></div><div className="event-info"><p className="event-meta">{e.category} <span>·</span> {e.city}</p><h3>{e.title}</h3><p>Palenque · Feria Nacional de Tijuana</p></div><span className={`date-status ${e.date < today ? 'past' : ''}`}>{e.date < today ? 'Fecha pasada' : e.date === today ? 'Hoy · consulta horario' : 'Fecha anunciada'}</span><a href={source} target="_blank" rel="noopener noreferrer" className="event-link" aria-label={`Consultar ${e.title} en la cartelera oficial`}>Ver cartelera <Arrow/></a></article>) : <div className="empty"><h3>{city === 'Todas las ciudades' ? 'Estamos buscando los próximos encuentros.' : `La agenda de ${city} está por crecer.`}</h3><p>Aún no tenemos nuevas fechas verificadas para esta selección. Mientras tanto, descubre las experiencias y consulta la programación directamente con sus organizadores.</p><button onClick={() => {setCity('Todas las ciudades');setPeriod('todos');}}>Consultar la edición de septiembre de 2026 <Arrow/></button></div>}</div>
        <div className="source-note"><p>Selección consultada el 4 de septiembre de 2026. Horarios, precios y disponibilidad: con el organizador.</p><a href={source} target="_blank" rel="noopener noreferrer">Fuente de la cartelera <Arrow/></a></div>
      </section>

      <section className="experience-section" id="experiencias"><div className="wrap section"><div className="section-heading"><div><p className="eyebrow wine">MÁS ALLÁ DEL FIN DE SEMANA</p><h2>Hay un rancho.<br/>Hay una <em>historia.</em></h2></div><p>Acércate a los caballos, aprende algo nuevo<br/>y encuentra otra forma de disfrutar el norte.</p></div><div className="experience-grid"><div className="experience-photo"><img src="/rancho.webp" loading="lazy" alt="Escena ilustrativa de vida ecuestre junto a un corral"/><span>EL GUSTO DE VOLVER AL CAMPO</span></div><div className="experience-options"><article><span className="number">01</span><div><p className="eyebrow">TIJUANA · RANCHO CASIAN</p><h3>Tu primera clase de monta</h3><p>El rancho anuncia clases para principiantes y avanzados. Consulta el nivel, equipo y acompañamiento antes de reservar.</p><a href="https://ranchocasian.com/clases-de-monta/" target="_blank" rel="noopener noreferrer">Consultar clases <Arrow/></a></div></article><article><span className="number">02</span><div><p className="eyebrow">TIJUANA · RANCHO CASIAN</p><h3>Un día para salir a caballo</h3><p>Una cabalgata puede ser el comienzo de un buen plan. El establecimiento anuncia esta actividad; confirma sus próximas salidas.</p><a href="https://ranchocasian.com/" target="_blank" rel="noopener noreferrer">Consultar cabalgatas <Arrow/></a></div></article><p className="experience-note">Actividades anunciadas, sujetas a disponibilidad. Las reservas y el servicio se gestionan directamente con el establecimiento.</p></div></div></div></section>

      <section id="historias" className="wrap section stories"><div className="section-heading"><div><p className="eyebrow wine">EL NORTE SE CUENTA</p><h2>Raíces que <em>se viven.</em></h2></div><span className="editorial-stamp">GUÍAS PARA EMPEZAR</span></div><div className="story-grid">{stories.map(s => <article className="story" key={s.id}><img src={s.image} alt={s.alt} loading="lazy"/><div className="story-body"><p className="eyebrow wine">{s.tag}</p><h3>{s.title}</h3><p>{s.intro}</p><details><summary>Leer la guía <Arrow/></summary><div className="story-text">{s.paragraphs.map(p => <p key={p}>{p}</p>)}<a href={s.source} target="_blank" rel="noopener noreferrer">{s.sourceLabel} <Arrow/></a></div></details></div></article>)}</div></section>

      <section className="directory wrap" id="directorio"><div><p className="eyebrow wine">DÓNDE ENCONTRARLO</p><h2>El estilo también<br/>tiene <em>sus lugares.</em></h2></div><article><span className="directory-icon" aria-hidden="true">C.</span><div><p className="eyebrow">ROPA, CALZADO Y ACCESORIOS</p><h3>Cuadra · Tijuana Hipódromo</h3><p>Consulta la sucursal y confirma tallas y productos directamente con la tienda.</p><a href="https://cuadra.com.mx/a/store-locator/cuadra-tijuana-hipodromo.html" target="_blank" rel="noopener noreferrer">Ver tienda oficial <Arrow/></a></div></article><p className="directory-note">Referencia editorial. La aparición de un negocio no implica patrocinio ni alianza comercial.</p></section>

      <section className="community" id="comunidad"><div className="wrap community-inner"><div><p className="eyebrow">UNA FRONTERA. MUCHAS HISTORIAS.</p><h2>El norte es grande.<br/>Lo que nos une,<br/><em>todavía más.</em></h2></div><div><span className="community-star" aria-hidden="true">✦</span><p>Desde Tijuana hasta Mexicali, de San Quintín a San Diego. Hay muchas formas de vivir lo vaquero y este es un lugar para encontrarnos.</p><p>Vida Vaquera del Norte reúne planes, lugares y guías para quienes disfrutan los caballos, la música, el estilo y las tradiciones de nuestra región.</p><p className="community-signature">UN MEDIO DE MEDIOS DE INTERESES ACTIVOS</p></div></div></section>

      <section className="partners wrap section" id="anunciantes"><div><p className="eyebrow wine">NEGOCIOS QUE COMPARTEN EL CAMINO</p><h2>Tu marca tiene<br/>una historia <em>aquí.</em></h2></div><div><p>Estamos preparando propuestas para negocios que quieran conectar con esta comunidad: patrocinios de agenda, contenido identificado como patrocinado y producción audiovisual.</p><details><summary>Explorar formas de colaboración <Arrow/></summary><div className="partner-options"><p><strong>Agenda patrocinada.</strong> Presencia de marca junto a la selección de planes y eventos.</p><p><strong>Contenido con tu marca.</strong> Historias y guías comerciales claramente identificadas.</p><p><strong>Producción audiovisual.</strong> Material para mostrar tu lugar, producto o experiencia.</p><p>Las propuestas se definirán según objetivos y alcance disponible. Actualmente no anunciamos cifras de audiencia ni patrocinadores confirmados.</p><a href="/colaboraciones.txt" download>Descargar resumen de colaboración ↓</a></div></details></div></section>
    </main>
    <footer><div className="wrap footer-top"><a href="#inicio" aria-label="Vida Vaquera del Norte, volver al inicio"><Brand/></a><p>El norte se vive.<br/>Y se comparte.</p><a href="#inicio" className="back-top" aria-label="Volver al inicio">↑</a></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Vida Vaquera del Norte · Un medio de <a href="https://medios-interes-activos.vercel.app/" target="_blank" rel="noopener noreferrer">MIA</a></span><a href="#anunciantes">Para anunciantes</a></div><p className="wrap image-credit">Fotografías conceptuales generadas con IA; no representan los establecimientos ni los eventos mencionados.</p></footer>
  </>;
}
